dream_house/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('dream_houses.urls'))
]

dream_houses/urls.py
# defining url patterns for dream_houses
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views
app_name = 'dream_houses'

urlpatterns = [
	# Home page name
	path('', views.index, name ='index'),
	path('dashboard/', views.dashboard, name = 'dashboard'),
	# Page for adding a new property
	path('new_property/', views.new_property, name ='new_property'),
	#Detail page for editing an entry
	path('edit_property/<int:property_id>/', views.edit_property, name = 'edit_property'),
	path('logout/', views.logout_view, name = 'logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# defining url patterns for dream_houses
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views
app_name = 'users'

urlpatterns = [
	# Home page name
	path('', include('django.contrib.auth.urls')),	
	# Registration page
	path('register/', views.register, name = 'register'),
]

dream_houses/models.py
from django.db import models
from django.contrib.auth.models import User

class Property(models.Model):
    PROPERTY_TYPES = [
        ('Buy', 'Buy'),
        ('Rent', 'Rent'),
    ]

    name = models.CharField(max_length=200)
    price = models.IntegerField()
    image = models.ImageField(upload_to='property_images/', null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    property_type = models.CharField(max_length=4, choices=PROPERTY_TYPES, default='Buy')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'properties'

users/models.py
from django.db import models

# Create your models here.

dream_houses/forms.py
from django import forms
from .models import Property

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ['name', 'price','image', 'property_type']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'Property'}),
            'price': forms.NumberInput(attrs={'class': 'Property'}),
            'property_type':forms.TextInput(attrs={'class':Property}),
        }
        enctype = "multipart/form-data"  # Make sure this line is present

dream_houses/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import logout
from .models import Property
from .forms import PropertyForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.

def index(request):
	properties = Property.objects.all()
	#Home page for learning logs
	return render(request, 'dream_houses/index.html', {'properties':properties})
@login_required
def dashboard(request):
	properties = Property.objects.filter(owner=request.user).order_by('date_added')
	#Home page for learning logs
	return render(request, 'dream_houses/dashboard.html', {'properties':properties})

@login_required
def new_property(request):
    if request.method != 'POST':
        form = PropertyForm()
    else:
        # Post data submitted, process data
        form = PropertyForm(request.POST, request.FILES)
        if form.is_valid():
            new_property = form.save(commit=False)
            new_property.owner = request.user
            new_property.save()
            return redirect('dream_houses:dashboard')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'dream_houses/new_property.html', context)



def edit_property(request, property_id):
    property_instance = Property.objects.get(id=property_id)

    if request.method == 'POST':
        form = PropertyForm(request.POST, request.FILES, instance=property_instance)
        if form.is_valid():
            form.save()
            return redirect('dream_houses:dashboard')
    else:
        form = PropertyForm(instance=property_instance)

    context = {'property': property_instance, 'form': form}
    return render(request, 'dream_houses/edit_property.html', context)


def logout_view(request):
    logout(request)
    messages.success(request, 'You have logged out.')
    return redirect('dream_houses:index')

users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login

from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
	# Register a new user
	if request.method != 'POST':
		form = UserCreationForm()
	else:
		#Post data submitted, process data
		form = UserCreationForm(data = request.POST)
		if form.is_valid():
			new_user = form.save()
			#log the user in then redirect to the home page
			login(request,new_user)
			return redirect('dream_houses:index')
	#Display a blank or invalid form

	context = {'form': form}
	return render(request, 'registration/register.html', context)

dream_houses/templates/dream_houses/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ndjekornom Victoire</title>
    <link rel="stylesheet" href="static/css/styles.css">
    <script src="https://kit.fontawesome.com/fe02953daa.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="header">
        <div class="container" >
            <nav>
                <h1 class="logo"><span>N</span>djek.</h1>
                
                <ul id="sidemenu">
                    <li><a href="{% url 'dream_houses:index' %}">Home</a></li>
                    
                    
                    <li><a href="{% url 'users:login' %}">Login</a></li>
                    <li><a href="{% url 'users:register' %}">Register</a></li>
                    
                    <i class="fas  fa-times" onclick="closemenu()"></i>
                </ul>
                <i class="fas fa-bars" onclick="openmenu()"></i>
                
            </nav>
            <div class="header-text">
                <p>Hi there !!!</p>
                <h1>Find the <span>Home</span>  of <br> your dreams</h1>
</div>
        </div>
    </div>
    <div >
            {% block page_header%}{% endblock page_header%} 
        </div>
        <div>
            {% block content %}{% endblock content %}   
        </div>

</body>
</html>

dream_houses/templates/dream_houses/dashboard.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ndjekornom Victoire</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <script src="https://kit.fontawesome.com/fe02953daa.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="header">
        <div class="container" >
            <nav>
                <h1 class="logo"><span>N</span>djek.</h1>
                
                <ul id="sidemenu">
                    <li><a href="{% url 'dream_houses:index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                   <li >
                <span >
                Hello, {{user.username}}
                </span>
            </li>
            <li class="nav-item">
                <form class="form-inline my-2 my-lg-0" action="{% url 'dream_houses:logout' %}" method="post">
                    {% csrf_token %}
                <button class="btn " type="submit"> 
                Log out</button>
                <input type="hidden" name="next" value="{% url 'dream_houses:index' %}">
                </form>
            </li>
            {% endif %}
                    
                    <i class="fas  fa-times" onclick="closemenu()"></i>
                </ul>
                <i class="fas fa-bars" onclick="openmenu()"></i>
                
            </nav>
            <div class="header-text">
                <h1>Welcome <span>to your dashboard.</span>   <br> Manage your properties here.</h1>
           </div>
           <a href="{% url 'dream_houses:new_property' %}" class="btn btn2">Add a property</a>
           <a href="#properties" class="btn btn2">View Properties</a>
        </div>
    </div>
    
<div id="properties">
    <div class="container">
        <h1 class="subtilte">
                    My Properties
            </h1>

        <div class="property-list">
        {% for property in properties %}
        <div class="property">
                    {% if property.image %}
                    <img src="{{ property.image.url }}" alt="{{ property.name }}">
                {% endif %}
                    <div class="layer">
                        <h3>Name: {{ property.name }}</h3>
                        <p>Price: {{ property.price }}</p>
                            <a href="{% url 'dream_houses:edit_property' property.id %}">Edit</a>
                    </div>
        </div>
           
        {% endfor %}
    </div>
        
    </div>
    
</div>

    
<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

dream_houses/templates/dream_houses/edit_property.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ndjekornom Victoire</title>
   <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://kit.fontawesome.com/fe02953daa.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="header-edit">
        <div class="container" >
            <nav>
                <h1 class="logo"><span>N</span>djek.</h1>
                
                <ul id="sidemenu">
                    <li><a href="{% url 'dream_houses:dashboard' %}">Dashboard</a></li>
                   
                    
                    <i class="fas  fa-times" onclick="closemenu()"></i>
                </ul>
                <i class="fas fa-bars" onclick="openmenu()"></i>
                
            </nav>
         
        </div>
    </div>

    <div class="container-new">
    	<h1 class="subtitle">
    	Editing:
    	 {{property.name}} 
    </h1>
    	
    </div>
    
        <div class="contact-right">
                   <form action="{% url 'dream_houses:edit_property' property.id %}" method="post" enctype="multipart/form-data">


	{% csrf_token %}
	{{form.as_p}}
	<button name="submit" class="btn btn2">Save changes</button>
	
</form>
                    <span id="msg"></span>

                </div>

</body>
</html>

dream_houses/templates/dream_houses/index.html
{% extends "dream_houses/base.html" %}

{% block page_header %}

    
{% endblock page_header %}

{% block content %}
 <div id="about">
        {% for property in properties %}
        <div class="container">
            
            <div class="row">
                
                <div class="about-col-1">
                    {% if property.image %}
                    <img src="{{ property.image.url }}" alt="{{ property.name }}">
                   {% endif %}

                </div>
                <div class="about-col-2">
                    
                    <div class="about-col-2-1">
                        <p>
                            <h2>
                               Name: {{property.name}}
                            </h2>
                        </p>
                        <p>
                            Type: {{property.property_type}}
                        </p>
                        <p>
                            Price: {{property.price}}
                        </p>
                        
                    </div>
                    <div class="about-col-2-2">
                        <p>
                            <h2>
                                Description
                            </h2>
                            <p>{{property.bathrooms}}</p>
                            <p>{{property.bedrooms}}</p>
                        </p>

                    </div>
                    <div class="about-col-2-3">
                        <p>
                            <h2>
                                Owner contact
                            </h2>
                        </p>
                        <p>
                            {{property.owner.email}}
                        </p>
                        <a href="mailto:{{property.owner.email}}" class="btn btn2">Contact owner</a>

                        
                    </div>
                    
                </div>
                
            </div>
        </div>
        {% endfor %}
    </div>
    
{% endblock content %}

dream_houses/templates/dream_houses/new_property.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ndjekornom Victoire</title>
   <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://kit.fontawesome.com/fe02953daa.js" crossorigin="anonymous"></script>
</head>
<body>
    <div id="header-new">
        <div class="container" >
            <nav>
                <h1 class="logo"><span>N</span>djek.</h1>
                
                <ul id="sidemenu">
                    <li><a href="{% url 'dream_houses:dashboard' %}">Dashboard</a></li>
                    
                    
                    <i class="fas  fa-times" onclick="closemenu()"></i>
                </ul>
                <i class="fas fa-bars" onclick="openmenu()"></i>
                
            </nav>
         
        </div>
    </div>
    <div class="container-new">
    	<h1 class="subtitle">
    	 Adding new property
    </h1>
    </div>
    
    
    <div class="contact-right">
                  <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn2">
                Add</button>
                </form>
                    <span id="msg"></span>

                </div>

</body>
</html>